### ISSUE TITLE
Failed to read row 0, column 4294967295 from a window with 1 rows, 0 columns

### ISSUE THREAD

**Issue by jmhe1** [javakam/FileOperator#101]
手机型号：iQOO 10
Android版本：13
问题详情；
   从微信选择第三方软件打开，调用String absolutePath = FileUri.INSTANCE.getPathByUri(uri);报错：Failed to read row 0, column 4294967295 from a window with 1 rows, 0 columns
![b7e28475def63a25ce956a4c1fe7a8f](https://github.com/javakam/FileOperator/assets/16079286/c312b014-7760-4898-859e-b9c8cad018aa)

**Comment by javakam** [comment]
别用path, 用uri 
![image](https://github.com/javakam/FileOperator/assets/15343661/35336348-59a5-4925-9b65-ffb48342425e)
