### ISSUE TITLE
鸿蒙4.0的系统 文件没有权限访问

### ISSUE THREAD

**Issue by fbu11** [javakam/FileOperator#104]
![微信截图_20240424104323](https://github.com/javakam/FileOperator/assets/28282479/d76dac33-f606-4263-94fa-d428c2104d87)
文件能选，但要用okhttp上传时报错
read failed: ENOTCONN
sdk用的是最新版

**Comment by javakam** [comment]
看下怎么上传的, 来点代码

**Comment by fbu11** [comment]
很基础的okthhp上传代码，几百KB的文件都不需要切片
 okHttpClient.newCall(
            Request.Builder().url(Urls.UPLOAD_SINGLE).post(
                MultipartBody.Builder().setType(MultipartBody.FORM)
                    .addFormDataPart("file", file.name, file.asRequestBody(MEDIA_TYPE_OCTET))
                    .build()
            ).build()
        ).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) = dealException(e, callback)

            @Throws(IOException::class)
            override fun onResponse(call: Call, response: Response) = dealResponse(
                response, hasToken = false, callback = callback
            )
        })

**Comment by javakam** [comment]
😅这是okhttp使用上的问题, 你再研究研究。AI是这么解答的你可以试试 : 

![image](https://github.com/javakam/FileOperator/assets/15343661/30bca034-7490-43b8-ad55-c1e7adac7a18)

**Comment by fbu11** [comment]
不是😅，这问题只在鸿蒙HarmonyOS 4.0 4.2的系统出现，其它手机Android13、Android14、HarmonyOS3.0、HarmonyOS2.0都没事

**Comment by fbu11** [comment]
AI就是屎

**Comment by fbu11** [comment]
鸿蒙也是屎，想让开发者开发，又不完全开放平台API
