### ISSUE TITLE
在小米和华为手机上存在bug

### ISSUE THREAD

**Issue by lhholylight** [javakam/FileOperator#11]
小米和华为手机上选择文件会出现一个错误报告的选项，里面的文件无法获取到真实路径，且小米下载目录下的文件也无法获取到真实路径。

**Comment by javakam** [comment]
能详细描述下具体操作流程吗, 还有版本信息

**Comment by lhholylight** [comment]
点击获取文件uri/path,进入后选择文件，选择下载内容或者错误报告里面的文件，miui11

**Comment by javakam** [comment]
在提供下FileOperator的版本, 和错误log.... 我这用的都很正常啊....  你用的是单选文件功能还是多选

**Comment by lhholylight** [comment]
直接下载源码运行的

**Comment by javakam** [comment]
😅...不应该啊, 方便录个小视频吗, 发我qq上 1772664927

**Comment by javakam** [comment]
Fixed: https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java 

找了很多资料 , 感觉还是这种方式靠谱, 应该是访问公共目录都会有这个问题...  解决方式是把这个文件复制到另外一个目录,然后获取路径....

### 参考
https://stackoverflow.com/questions/42508383/illegalargumentexception-column-data-does-not-exist
https://stackoverflow.com/questions/30671548/unknown-url-content-downloads-my-downloads/53021624
https://github.com/zendesk/sunshine-conversations-android/issues/131

首先这么用肯定没问题, 不过不是最好的方式, 先发布`1.3.5`版本用着.  我觉得问题应该在**contentResolver赋予权限**上, 还得继续抽时间研究
