### ISSUE TITLE
获取到的txt文件的path为null

### ISSUE THREAD

**Issue by yangpotato** [javakam/FileOperator#32]

**Comment by javakam** [comment]
安卓版本是多少，是miui还是emui或是其他系统，还有该txt所在目录在哪，才能定位问题所在。

**Comment by yangpotato** [comment]
Android版本：11   小米10

**Comment by yangpotato** [comment]
Android 版本：11
机型：小米10
miui版本：12.2.9
![Screenshot_2021-05-15-10-23-46-441_com ando file](https://user-images.githubusercontent.com/27049872/118345531-b81b7c00-b567-11eb-86b4-3e4084522180.jpg)

文件目录：Downloads

**Comment by javakam** [comment]
参考 #21 

Android11上不支持访问公共目录的path了，可以改用uri处理文件操作
