### ISSUE TITLE
content://media/external_primary

### ISSUE THREAD

**Issue by bingdu0** [javakam/FileOperator#34]
您好 ，请问这种Uri 怎么获取路径

**Comment by javakam** [comment]
https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileUri.kt

具体用法在Demo里

**Comment by bingdu0** [comment]
> https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileUri.kt
> 
> 具体用法在Demo里

嗯嗯 这个我看了 ，不知道为什么 这种 content://media/external_primary  的Uri   调用getPathByUri()  后转换成file后 file 的size 为 zero  ，然后我用getDataColumn  这个获取到之后转file 就是有值的  。手机是华为mate20 pro

**Comment by javakam** [comment]
试试 v1.6.0 版本, 做了很多的修改

**Comment by bingdu0** [comment]
FileUri  的这个 fun getPathByUri(uri: Uri?): String? 中的  else if ("content".equals(uri.scheme, ignoreCase = true))  这段逻辑中的   最终的return getDataColumn(uri)    最通用的方法就是把文件copy 一份，然后在获取真实路径。

**Comment by bingdu0** [comment]
> 试试 v1.6.0 版本, 做了很多的修改。 有问题再反馈

好的  ，我试一下
