### ISSUE TITLE
只显示文档的文件

### ISSUE THREAD

**Issue by zhouzl18** [javakam/FileOperator#35]
如何设置只显示文档的文件，就像Demo里面的“选择一张图片并压缩”，进去只能看到图片。
setMimeTypes(
                        "application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document", // .doc & .docx
                        "application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation", // .ppt & .pptx
                        "application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", // .xls & .xlsx
                        "application/pdf");
                        
我是这样设置的，虽然只能选择doc、excel、pdf，但是图片还有其他文件还是会显示出来，只是不能选择。

**Comment by javakam** [comment]
这个得看不同的系统版本吧，我记得有的系统是过滤掉的，有的是一块儿显示出来但不能选择。。晚上回去再实验看看，之前还没特别注意这一点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月29日(周六) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [javakam/FileOperator] 只显示文档的文件 (#35)




 
如何设置只显示文档的文件，就像Demo里面的“选择一张图片并压缩”，进去只能看到图片。
 setMimeTypes(
 "application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document", // .doc &amp; .docx
 "application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation", // .ppt &amp; .pptx
 "application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", // .xls &amp; .xlsx
 "application/pdf");
 
我是这样设置的，虽然只能选择doc、excel、pdf，但是图片还有其他文件还是会显示出来，只是不能选择。

**Comment by javakam** [comment]
@zhouzl18  刚又查了下官方文档, 在限定类型以外的其他类型文件是不能选择, 但是还是会显示出来, 我在AndroidQ运行出来是这样的

In FileSelectMultiFilesActivity : 
```kotlin
...setMimeTypes("audio/*", "image/*", "text/*")
```

<img loading="lazy" src="https://user-images.githubusercontent.com/15343661/120068026-2ce6ce00-c0b1-11eb-90df-3da30c666f60.png" alt="ScreenShot" width="260" height="520">


🍎官方文档 : https://developer.android.google.cn/training/data-storage/use-cases?hl=zh-CN

![image](https://user-images.githubusercontent.com/15343661/120068094-8d760b00-c0b1-11eb-9629-3d5e5027d2ac.png)

🍎Android文件打开被单独封装到了<https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileOpener.kt>
