### ISSUE TITLE
android 10 压缩 返回的uri 路径异常

### ISSUE THREAD

**Issue by smileToWxm** [javakam/FileOperator#38]
这边尝试了  ImageCompressor.Companion.with，ImageCompressEngine.INSTANCE.compressCompat ，2中方法，图片虽然成功压缩到目录下，但是 通过回调 setImageCompressListener 返回的uri 路径不对，  targetDir的路径为 /data/user/0/app2.dfhondoctor.com/cache/smartcity_disk_save_cache，但是返回的uri路径为content:/app2.dfhondoctor.com.andoFileProvider/ando_cache/smartcity_disk_save_cache/162314443047292.jpeg，
   ando_cache 这个路径有误，导致我后续找不到对应的文件

**Comment by javakam** [comment]
1. 方便的话贴一下具体代码或是抽取出问题代码我好复现该问题。
2. 还有路径Path和Uri是两个不同的东西，前面那个"data/…"是内部存储路径，而"content://…"和"file://…"是安卓以6.0为分界不同系统版本的文件分享需要的Uri地址，这个地址并不是路径，不能直接使用File去解析。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月8日(周二) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [javakam/FileOperator] android 10 压缩 返回的uri 路径异常 (#38)




 
这边尝试了  ImageCompressor.Companion.with，ImageCompressEngine.INSTANCE.compressCompat ，2中方法，图片虽然成功压缩到目录下，但是 通过回调 setImageCompressListener 返回的uri 路径不对，  targetDir的路径为 /data/user/0/app2.dfhondoctor.com/cache/smartcity_disk_save_cache，但是返回的uri路径为content:/app2.dfhondoctor.com.andoFileProvider/ando_cache/smartcity_disk_save_cache/162314443047292.jpeg，
 ando_cache 这个路径有误，导致我后续找不到对应的文件

**Comment by smileToWxm** [comment]
> 1. 方便的话贴一下具体代码或是抽取出问题代码我好复现该问题。 2. 还有路径Path和Uri是两个不同的东西，前面那个"data/…"是内部存储路径，而"content://…"和"file://…"是安卓以6.0为分界不同系统版本的文件分享需要的Uri地址，这个地址并不是路径，不能直接使用File去解析。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月8日(周二) 下午5:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [javakam/FileOperator] android 10 压缩 返回的uri 路径异常 (#38) 这边尝试了 ImageCompressor.Companion.with，ImageCompressEngine.INSTANCE.compressCompat ，2中方法，图片虽然成功压缩到目录下，但是 通过回调 setImageCompressListener 返回的uri 路径不对， targetDir的路径为 /data/user/0/app2.dfhondoctor.com/cache/smartcity_disk_save_cache，但是返回的uri路径为content:/app2.dfhondoctor.com.andoFileProvider/ando_cache/smartcity_disk_save_cache/162314443047292.jpeg， ando_cache 这个路径有误，导致我后续找不到对应的文件 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边用demo的例子也会出现，FileSelectSingleImageActivity ，在compressImage的压缩成功后的回调内执行 FileUri.getPathByUri(u)，得到的路径为空，部分图片会出现这样的场景，虽然图片还是显示出来了，但是获取不到对应的文件路径

**Comment by javakam** [comment]
AndroidQ 和 11 确实存在路径找不到的问题:

https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileUri.kt

![image](https://user-images.githubusercontent.com/15343661/121465056-afdc2280-c9e7-11eb-8c8d-d7112dbe5a51.png)

🍎 基本上绝大多数 issue 都是问这个的 , 详细解释可以看 #21 

这个框架是在不设置requestLegacyExternalStorage 操作的,  如果必需要路径的话可以尝试在应用的清单文件中将 requestLegacyExternalStorage 设置为 true , 并配置好 `READ_EXTERNAL_STORAGE` 权限。
