### ISSUE TITLE
有木有java版本?大佬~

### ISSUE THREAD

**Issue by ILoveLin** [javakam/FileOperator#50]
有木有java版本?大佬~

**Comment by javakam** [comment]
以前有java使用案例, 后来版本就给删掉了 <https://github.com/javakam/FileOperator/tree/v1.3.6>

**Comment by ILoveLin** [comment]
为啥呀,大佬,kotlin不是很熟悉,有java就好了,项目很赞~

**Comment by javakam** [comment]
谢谢捧场, 因为一开始写这个用的就是Kotlin, 所以也就没有Java版本. 不过Java项目也是可以用的, 不过得引入Kotlin的那些东西

**Comment by ILoveLin** [comment]
恩恩,好的,谢谢哈~
