### ISSUE TITLE
有做指定目录的，基本文件类型统计吗

### ISSUE THREAD

**Issue by renwfy** [javakam/FileOperator#56]
例如文件管理器一样，统计基本文件类型和大小，还是的自己扫描处理

**Comment by javakam** [comment]
是选择一些文件后, 对选出来的这些文件进行一个区分, 包括类型、大小、路径等
```kotlin
//选择结果
data class FileSelectResult(
    var fileType: @RawValue IFileType?,
    var mimeType: String?,
    var uri: Uri?,
    var filePath: String?,
    var fileSize: Long = 0L,
)
```

**Comment by renwfy** [comment]
选择文件的话，得手动指定目录，然后来判断。可以实现指定目录就开始扫描统计吗

**Comment by renwfy** [comment]
或者说是指定某个目录路径

**Comment by javakam** [comment]
目前还不支持这种操作, 现在是手动进入目录对选择结果进行处理...

**Comment by javakam** [comment]
具体需求是什么样的, 可以改一改.  这个想法不错

**Comment by renwfy** [comment]
其实就是一个基本的文件管理器，管理一些大应用的目录数据，清理啊这类的，现在就再Android 11 比较麻烦。
![WechatIMG647](https://user-images.githubusercontent.com/6526280/134636132-cc068208-dde0-4bb5-ba5d-3493420ca10c.jpeg)

**Comment by javakam** [comment]
Android11+ 版本确实让人很无语...
