### ISSUE TITLE
自定义 fileTypeMismatchTip 不起作用

### ISSUE THREAD

**Issue by SSSSunrise** [javakam/FileOperator#62]
![image](https://user-images.githubusercontent.com/31717774/143564442-bcc4e373-f1d0-4f34-b324-f5c907024d21.png)
![image](https://user-images.githubusercontent.com/31717774/143564507-966fb923-378d-4fc3-90bf-9482ec4c9eab.png)

**Comment by javakam** [comment]
已经改好了, 稍后更新版本 v2.4.0
![image](https://user-images.githubusercontent.com/15343661/143802269-fa391c2f-ff09-423e-ae70-6deff72db932.png)

问题在于之前是写死了一个失败的条件, 返回时候没有动态再赋值:
`private val optionUnknown: FileSelectOptions by lazy { FileSelectOptions().apply { fileType = UNKNOWN } }`

![image](https://user-images.githubusercontent.com/15343661/143802504-7f72cc59-fe55-4293-af95-88964666b883.png)

**Comment by SSSSunrise** [comment]
ok，稍后我更新看看

**Comment by javakam** [comment]
方法位置👉https://github.com/javakam/FileOperator/blob/master/app/src/main/java/com/ando/file/sample/ui/selector/fragment/FileSelectFragment.kt 👉 `testIssue62()`
