### ISSUE TITLE
all class was empty

### ISSUE THREAD

**Issue by Traveler1991** [javakam/FileOperator#68]
![image](https://user-images.githubusercontent.com/13065967/150083829-2adc4f39-6a90-4b3a-9cc7-cdfe4dde6dcb.png)

**Comment by javakam** [comment]
项目的 `build.gradle` 中加上 这个 `maven { url "https://s01.oss.sonatype.org/content/groups/public" }`

![image](https://user-images.githubusercontent.com/15343661/150109945-9c2ccd7b-0731-4aeb-b765-6ae7bb4d515b.png)

之前都是好的, 不用配置这个也行, 这次不知道咋回事儿, 三个包一起传上去的就这个core获取不到

![image](https://user-images.githubusercontent.com/15343661/150110210-ff7626e4-8cd9-410b-b794-1b5ceb45b3ed.png)
