### ISSUE TITLE
android 11 删除DCIM 下的图片一直失败，怎么办啊？

### ISSUE THREAD

**Issue by wangya123456789** [javakam/FileOperator#70]
Android10以下都没有问题，我看官网说，需要对删除的文件单独申请权限才可以，库里的哪个API可以快速实现？？

**Comment by easyy2021** [comment]
core里面的FileUtils和MediaStoreUtils都有删除功能，你试试哪个没问题就用哪个。。成功了别忘了告诉我一声

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月20日(周四) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [javakam/FileOperator] android 11 删除DCIM 下的图片一直失败，怎么办啊？ (Issue #70)




 
Android10以下都没有问题，我看官网说，需要对删除的文件单独申请权限才可以，库里的哪个API可以快速实现？？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by javakam** [comment]
core里面的FileUtils和MediaStoreUtils都有删除功能，你试试哪个没问题就用哪个。。成功了别忘了告诉我一声

**Comment by wangya123456789** [comment]
> core里面的FileUtils和MediaStoreUtils都有删除功能，你试试哪个没问题就用哪个。。成功了别忘了告诉我一声

我试了，但是都不行啊，要不你试一下，谢谢

**Comment by javakam** [comment]
`MediaStoreUtils`是好的

```kotlin
MediaStoreUtils.deleteFile(文件uri)

//MediaStoreUtils.kt
fun deleteFile(uri: Uri): Boolean {
    if (checkUriColumnFlag(uri, DocumentsContract.Document.FLAG_SUPPORTS_DELETE)) {
        return DocumentsContract.deleteDocument(FileOperator.getContext().contentResolver, uri)
    }
    return false
}
```
