### ISSUE TITLE
文件类型

### ISSUE THREAD

**Issue by jiayuliang1314** [javakam/FileOperator#73]
"text/csv" csv的得用"text/comma-separated-values",而不是 "text/csv",
“rtf”  rtf得用"text/rtf"而不是“application/rtf”

.setMimeTypes("application/msword",//doc
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",//docx
                        "application/pdf",
                        "application/vnd.ms-excel",//xls
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",//xlsx
                        "application/vnd.ms-powerpoint",//ppt
                        "application/vnd.openxmlformats-officedocument.presentationml.presentation",//pptx
                        "text/csv",
                        "text/comma-separated-values",
                        "text/plain",
                        "text/rtf")

**Comment by javakam** [comment]
一个文件对应的`MimeType`可能有多种,  框架提供以下两种方式进行补充: 

![image](https://user-images.githubusercontent.com/15343661/157592431-4fc0ea1f-9fb7-46f6-b461-95d42e1d40ce.png)

或者直接自定义 :

![image](https://user-images.githubusercontent.com/15343661/157592500-147923bc-f3ca-4f51-9df3-6fd5ee6ea0a1.png)

---
---

[`FileMimeType.kt`](https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileMimeType.kt) 中的`MIME_TABLES` 是在`MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension)`的一种补充, 基本上也调用不到, 建议使用上面的方案。

**Comment by javakam** [comment]
"application/xxx" 是调用Android系统里面支持这种格式的软件打开,  比如设置“application/rtf”时候没响应, 可能是手机中没安装支持“application/rtf”的软件:
```
<!-- Demo App 清单中加入下面的配置就能够对"application/rtf"的启动请求产生响应  -->
<intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="application/rtf"/>
</intent-filter>
```
[`FileMimeType.kt`](https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileMimeType.kt) 之前参照了 <https://github.com/broofa/mime> 中的部分调整的, 后面会把相应的匹配逻辑搬过来, 感觉他这种匹配方式更全面 ... 替换掉 Android 提供 `MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension)`

**Comment by javakam** [comment]
已经修改了 [FileMimeType.kt](https://github.com/javakam/FileOperator/blob/master/library_core/src/main/java/ando/file/core/FileMimeType.kt) 的实现方案
