### ISSUE TITLE
适配一下 registerForActivityResult

### ISSUE THREAD

**Issue by wsdydeni** [javakam/FileOperator#76]
作为一个强迫症晚期患者，受不了黄色警告⚠

**Comment by javakam** [comment]
其实已经适配很久了... 
🌰  [FileSelectSingleImageActivity.kt](https://github.com/javakam/FileOperator/blob/master/app/src/main/java/com/ando/file/sample/ui/selector/FileSelectSingleImageActivity.kt)
🌰 Fragment 中 [FileSelectFragment.kt](https://github.com/javakam/FileOperator/blob/master/app/src/main/java/com/ando/file/sample/ui/selector/fragment/FileSelectFragment.kt)

**Comment by wsdydeni** [comment]
> 其实已经适配很久了... 🌰 Activity : [FileSelectSingleImageActivity.kt](https://github.com/javakam/FileOperator/blob/master/app/src/main/java/com/ando/file/sample/ui/selector/FileSelectSingleImageActivity.kt?rgh-link-date=2022-04-14T02%3A03%3A57Z) 🌰 Fragment : [FileSelectFragment.kt](https://github.com/javakam/FileOperator/blob/master/app/src/main/java/com/ando/file/sample/ui/selector/fragment/FileSelectFragment.kt?rgh-link-date=2022-04-14T02%3A03%3A57Z)

你可真是个绝绝子啊
