### ISSUE TITLE
怎么选择zip文件了，自定义类型选择ZIP,但是打开文件系统，选择不了

### ISSUE THREAD

**Issue by wypgh** [javakam/FileOperator#86]
![image](https://user-images.githubusercontent.com/52516741/231924901-0cd49f48-0422-422c-8f9b-f59273f3d34a.png)
  val optionsTxt = FileSelectOptions().apply {
            fileType = FileType.ZIP
            minCount = 1
            maxCount = 2
            minCountTip = "Select at least one text file"
            maxCountTip = "Select up to two text files"
            singleFileMaxSize = 5242880
            singleFileMaxSizeTip = "The maximum size of a single text file is 5 M!"
            allFilesMaxSize = 10485760
            allFilesMaxSizeTip = "The total size of the text file does not exceed 10 M!"
            fileCondition = object : FileSelectCondition {
                override fun accept(fileType: IFileType, uri: Uri?): Boolean {
                    return (uri != null)
                }
            }
        }

**Comment by javakam** [comment]
具体的错误信息是什么呢？

**Comment by javakam** [comment]
setOverLimitStrategy(OVER_LIMIT_EXCEPT_OVERFLOW)  改用这个试试

**Comment by wypgh** [comment]
谢谢  是我设置有问题。解决了

**Comment by javakam** [comment]
那就好

**Comment by javakam** [comment]
v3.7.0 之前不支持`minCount = 0`的限制并且在`OVER_LIMIT_EXCEPT_ALL`策略下报错返回不具体:

改动:
![image](https://user-images.githubusercontent.com/15343661/232361868-7a82c025-d744-4283-ab0d-b7bfe718bf95.png)

使用:
```kotlin
//图片 Image
val optionsImage = FileSelectOptions().apply {
fileType = FileType.IMAGE
minCount = 0
maxCount = 2
...}

//文本文件 txt
val optionsTxt = FileSelectOptions().apply {
fileType = FileType.TXT
minCount = 1
maxCount = 2
...}

FileSelector
            .with(this)
            .setMultiSelect()
            .setOverLimitStrategy(OVER_LIMIT_EXCEPT_ALL)
            .setExtraMimeTypes("image/*", "text/*")
            .applyOptions(optionsImage, optionsTxt)
```
当选择一个`txt`文件时候现在会正常返回，但是如果只选了一个图片文件会抛出异常"[TXT]类型文件至少选择(minCount)个"。当然如果是`OVER_LIMIT_EXCEPT_OVERFLOW`策略则两种情形都不会报错并正常返回, 推荐使用。

**Comment by javakam** [comment]
新版本 v3.7.0
