### ISSUE TITLE
拉取源码后编译运行在OPPO reno5 pro (android 13 /33)上 崩溃

### ISSUE THREAD

**Issue by Fly946334** [javakam/FileOperator#97]
点击去选择文件时,直接崩溃; 
![微信截图_20231215163926](https://github.com/javakam/FileOperator/assets/20764710/bb8b46a3-b7ee-4a9b-a457-a496c2500635)

**Comment by javakam** [comment]
看上去应该是 string 的资源文件没找到, 试试invalidate caches然后重新编译试试

**Comment by javakam** [comment]
很有可能是这个权限框架没有兼容13, 刚推送更新了权限框架版本 : 
![image](https://github.com/javakam/FileOperator/assets/15343661/afb0de6d-db7f-4cd3-b2d5-f9ea1a447248)
